Updated debug library version to avoid vulnerabilities scan error
import-js/eslint-plugin-import pull request #2177
Opened 2021-08-06 05:47 UTC by sandeshvijayraj

Debug Library < 4.1.1 in package.json was being detected as Vulnerable 

Updated Library to >4.1.3 that is considered to be non vulnerable

2021-08-06 05:52 UTC, ljharb requested changes
No. This is a breaking change.

2021-08-06 05:53 UTC, ljharb commented
See #2169, #1892, #868.

Most vulnerabilities are false positives and this one is no exception. Just ignore the warning.

2021-08-06 05:53 UTC, closed without merging

2021-08-06 06:32 UTC, sandeshvijayraj commented
Oh thanks for the info @ljharb I missed that comment earlier

2023-12-08 16:32 UTC, ljharb commented
@martinez-hugo see above why we can't.