[order] Sort type imports
import-js/eslint-plugin-import pull request #2398
Opened 2022-03-06 22:38 UTC by aaronadamsCA

Here's a preliminary PR that resolves #2339. It's my first contribution, so please bear with me! 🙂

- Type imports are now sorted before regular imports, because this appears to be the overwhelming ecosystem standard.
- To reduce ambiguity, error messages can now refer to "type import" instead of just "import".
- I included `typeof` support just in case (though I don't know much about Flow).
- Tests were updated to reflect revised behaviour, and two new tests were added.

I also did some opportunistic code cleanup:

- Some test messages seemed to reflect old non-deterministic rule behaviour with "before" vs. "after" errors. Given this is now predictable, I made the tests easier to understand and maintain.
- Coding style toward the end of the test file was all over the place, so I cleaned it up.
- I made a minor performance improvement in `fixOutOfOrder`.

Let me know if there's anything I should undo here, or separate into separate PRs.

2022-05-27 07:32 UTC, stropho commented
Hmm wondering what is this waiting for :) Anyway, if I was the maintainer, I would appreciate keeping the test coverage on the same level or higher.

A nice non-blocking improvement could be providing and option to sort type imports before/after the regular import. On the other hand that could be a different PR..

2022-05-27 14:39 UTC, ljharb requested changes
Thanks, this is great!

We need some more test coverage, and it needs to be rebased (there’s a conflict).

2022-05-27 14:39 UTC, ljharb commented on src/rules/order.js
> +    return 'typeof import';
Let’s add tests that cover this line

2022-05-27 14:39 UTC, ljharb commented on src/rules/order.js
> +    return alphabetizeOptions.caseInsensitive ? String(value).toLowerCase() : value;
This function can be hoisted to module level

2022-05-27 14:39 UTC, ljharb commented on src/rules/order.js
> +    return 0;
We need a test to cover this line too

2022-05-27 14:39 UTC, ljharb commented on tests/src/rules/order.js
> +              import c from 'Bar';
Changing existing tests implies it’s a breaking change. Can this test be reverted and a new one added?

2022-05-27 14:39 UTC, ljharb commented on tests/src/rules/order.js
> +              { message: '`bar` import should occur after import of `Bar`' },
does this test now report the same error, even in eslint 2?

2022-05-27 14:40 UTC, ljharb commented
Regarding separate PRs, i don’t think that’s necessary, but it would be nice when rebasing to group the “cleanup” stuff into its own commits, separate from the “fix and updated tests” commits.

2022-05-31 12:59 UTC, stropho commented
Hey @aaronadamsCA , how are you? What's the status? As this feature is very useful to me right now, I'm willing to help :) If you give me access to your fork, I could move this PR a bit further ;)

2022-05-31 14:24 UTC, ljharb commented
@stropho its only been 4 days over a holiday weekend, give it some time :-)

2022-09-07 04:57 UTC, ljharb approved these changes

2022-09-07 04:58 UTC, merged

2022-11-08 17:39 UTC, aaronadamsCA commented
Sorry, my contributions fell behind for a while due to offline things, so thank you for completing this!

2022-11-09 07:23 UTC, stropho commented
And now, finally publishing it after a while would be great :)