Add an option for `no-unresolved` rule that allows one to resolve .ts files from .js imports
import-js/eslint-plugin-import pull request #2483
Opened 2022-06-22 16:22 UTC by ukstv

One problem that prevents this package from being useable on TS codebase, is that it treats a file extension literally. TypeScript-based ES modules require you to import TS files using .js extension:
```
import * as foo from './foo.js'
```
The statement above really imports content of `./foo.ts` file.

This PR adds a new boolean option `ts`, set to `false` by default. If it is set to `true`, a statement above in a TS codebase is considered valid.

2022-06-22 16:33 UTC, ntucker commented
probably want to have it try .tsx as well

2022-06-22 16:47 UTC, ukstv commented
Okay, now it tries to resolve `.jsx?` to `.ts` or `.tsx`.

2022-06-24 07:45 UTC, Maxim-Mazurok requested changes
I think that some tests for this need to be added to https://github.com/import-js/eslint-plugin-import/blob/main/tests/src/rules/no-unresolved.js

2022-06-30 16:17 UTC, ukstv commented
@Maxim-Mazurok Added the tests. What is left for the PR to be merged?

2022-06-30 22:27 UTC, Maxim-Mazurok commented
Thanks! I think the only thing left is to get some maintainer to approve it. I didn't really check the code, but now that we have tests I think that maintainers approval is more likely to happen.

2022-07-01 09:19 UTC, ukstv commented
Good. Let me properly rebase that, and it is ready to merge then.

2022-07-01 12:26 UTC, ukstv commented
Rebased now. Hope it is good to merge. Feel free to add comments/critique, so that I can amend the PR.

2022-07-11 20:07 UTC, ljharb commented
Since this deals with TS-specific resolution, is there a reason this couldn't/shouldn't be an option on the TS eslint resolver? (cc @bradzacher)

2022-07-11 20:22 UTC, ukstv commented
Should it be a default there, or hidden behind a flag, like here?

2022-07-11 21:20 UTC, bradzacher commented
@ukstv consider raising an issue there to discuss with the maintainers! You may find there is already one?

2022-07-19 16:26 UTC, JounQin commented
I don't understand, https://github.com/import-js/eslint-import-resolver-typescript already supports `exports` field in `package.json`, this is an unnecessary change in the core module.

2022-07-19 16:28 UTC, ukstv commented
> I don't understand, https://github.com/import-js/eslint-import-resolver-typescript already supports `exports` field in `package.json`, this is an unnecessary change in the core module.

`exports` clause in `package.json` has nothing to do with this change. What we are trying to achieve is having a check if a local `./foo.js` exists because of corresponding `./foo.ts` exists.

2022-07-19 16:29 UTC, JounQin commented
> What we are trying to achieve is having a check if a local ./foo.js exists because of corresponding ./foo.ts exists.

It is also supported by https://github.com/import-js/eslint-import-resolver-typescript

2022-07-19 17:04 UTC, JounQin commented
As above, please use https://github.com/import-js/eslint-import-resolver-typescript instead.

2022-07-19 17:04 UTC, closed without merging

2022-07-19 17:27 UTC, ntucker commented
I cannot find the equivalent of "import/order" in [eslint-import-resolver-typescript](https://github.com/import-js/eslint-import-resolver-typescript).

2022-07-19 17:42 UTC, ljharb commented
How is that unsafe?

2022-07-19 18:00 UTC, JounQin commented
> [import-js/eslint-plugin-import#importextensions](https://github.com/import-js/eslint-plugin-import#importextensions) the docs probably need to be updated to recommend installing this instead of adding extensions which is unsafe?

I'm going to PR to add a section about TypeScript usage in README, if you want to do that, feel free to tell me and take it.