feat: add `context` into resolver arguments
import-js/eslint-plugin-import pull request #2519
Opened 2022-08-07 04:30 UTC by JounQin

close #2108

2022-08-08 00:56 UTC, JounQin commented
I just found I forget to add something like resolved ts compile options into the argument.

2022-08-13 04:16 UTC, JounQin commented
Friendly ping @ljharb

2022-08-13 05:39 UTC, ljharb commented
I'm moving slowly on this one because of the potential for breakage.

Specifically, "old utils + old plugin", and "new utils + new plugin", obviously will work fine. However, I need to convince myself that "new utils + old plugin" and "old utils + new plugin" will continue to work. I'm likely going to wait until I've released all the unreleased changes before merging this.

2022-08-30 00:08 UTC, JounQin commented
I should pass the flattened `tsconfig` instead of `tsCompilerOptions` for all edge cases.

2022-09-04 14:03 UTC, JounQin commented on src/ExportMap.js
> +const tsconfigCache = new Map();
I rename it as `tsconfigCache` because `tsconfig` is much common usage.

2022-09-26 21:19 UTC, MWhite-22 commented
Any chance this PR can get some love @ljharb? 

This PR helps resolve the eslint monorepo issues regarding looking for a single root tsconig vs individual package level tsconfigs.

2022-09-26 21:21 UTC, ljharb commented
@MWhite-22 https://github.com/import-js/eslint-plugin-import/pull/2519#issuecomment-1213751418

2022-09-26 21:25 UTC, MWhite-22 commented
> @MWhite-22 [#2519 (comment)](https://github.com/import-js/eslint-plugin-import/pull/2519#issuecomment-1213751418)

When you say "All of the unreleased changes", I am just trying to get a rough approximation for what that looks like. Are we talking a few weeks or a few months?

2022-09-26 21:27 UTC, ljharb commented
I don't cut releases on any particular timeline. It could be hours, or weeks.

2022-11-29 18:49 UTC, nVitius commented
@JounQin Looks like there's a very small merge conflict on your branch. Can you resolve so this PR can move into a mergeable state again?

@ljharb I just wanted to echo the sentiment that this would be great to have. Currently setting up a monorepo with TS and I would love to use this plugin.

Have you had more time to think about the inclusion of this PR?

2023-04-17 20:13 UTC, MWhite-22 commented
Wanted to check in and see if there might be any option to help contribute to getting this merged?

Would love to revive this feature as its a prerequisite to a few other packages.

2023-04-17 21:07 UTC, ljharb requested changes
I've rebased this PR and split it up into separate commits - the final commit is the one that I'm concerned about:
1. it has no tests - the tests are in the third commit, and relate to resolvers, but we need tests that relate to the ExportMap changes
2. is this potentially a breaking change, if someone's using an older version of eslint-module-utils, with the ExportMap changes?

2025-05-25 00:24 UTC, JounQin commented
> is this potentially a breaking change

So we just developed https://github.com/un-ts/eslint-import-context FYI, no additional params are needed now.

2025-05-25 06:43 UTC, JounQin commented
I'm not going to continue this PR, please open another one instead. And I recommend to integrate with https://github.com/un-ts/eslint-import-context so no extra params are required, but Node 4+ is not the target of `eslint-import-context`.

2025-05-25 06:44 UTC, closed without merging