fix: changed resolvedPath check to check if its not a string
import-js/eslint-plugin-import pull request #2886
Opened 2023-09-26 21:31 UTC by prisis

The "eslint-module-utils/resolve" returns 3 different types

- the full module filesystem path
- null if package is core
- undefined if not found

if null is returned from the resolve function the path.relative throws a error that i expects a string

Data passed into the resolve function.

```
resolve("../dist/postinstall", {
  id: 'import/no-useless-path-segments',
  options: [ { commonjs: true, noUselessIndex: true } ],
  report: [Function: report]
});
```

2023-09-26 23:34 UTC, ljharb requested changes
Can you provide a test case that fails without this change?

2023-09-27 06:57 UTC, prisis commented
Did dive a bit deeper into this issue, looks like this is the core of it, https://github.com/jsenv/core/blob/main/packages/independent/eslint-import-resolver/src/resolver.js#L282

2023-09-27 06:59 UTC, ljharb commented
That looks like a vendored and modified copy of one of this repo's packages? I'm very confused about that, so please keep me posted.

2023-09-27 07:10 UTC, prisis commented
Linking: https://github.com/jsenv/core/issues/379

2023-09-27 13:31 UTC, prisis commented
Will close this PR, the issue was fixed in the resolver package. Thank you for your time!

2023-09-27 13:31 UTC, closed without merging